# Generated by Django 5.1 on 2024-11-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block_list',
            name='ip',
        ),
        migrations.AddField(
            model_name='block_list',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, unique=True),
        ),
    ]
